# Generated by Django 5.2.3 on 2025-06-14 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name'], 'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.RemoveField(
            model_name='part',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='part',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='part',
            name='min_order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальный заказ'),
        ),
        migrations.AddField(
            model_name='part',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая цена'),
        ),
        migrations.AddField(
            model_name='part',
            name='wholesale_threshold',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порог для опта'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoparts.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розничная цена'),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
