# Generated by Django 5.2.3 on 2025-06-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0002_alter_part_options_remove_part_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
