# Generated by Django 5.2.3 on 2025-06-15 11:31

import autoparts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0004_alter_part_options_part_created_at_part_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterModelOptions(
            name='partdocument',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы заказа'},
        ),
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.CharField(default=autoparts.models.generate_sku, max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('client', 'Клиент')], default='client', max_length=10),
        ),
    ]
